import { BoardIR, ButtonIR, ActionIR } from '@/types/board-ir';
import { AacMaster, AacBoard, AacCell, AacAction, AacAssets } from '@shared/aac-master-schema';

export class AacMasterConverter {
  static convertFromBoardIR(board: BoardIR): AacMaster {
    const assets: AacAssets = {
      symbols: [],
      images: [],
      audio: [],
      videos: []
    };
    
    const symbolMap = new Map<string, string>();
    const videoMap = new Map<string, string>();
    
    // Convert boards
    const aacBoards: AacBoard[] = board.pages.map((page, pageIndex) => {
      const cells: AacCell[] = [];
      
      // Convert regular buttons
      page.buttons.forEach((button, buttonIndex) => {
        const cellId = `cell_${pageIndex}_${buttonIndex}`;
        
        // Handle symbol assets
        let symbolId: string | undefined;
        if (button.symbolPath) {
          const symbolName = button.symbolPath.split('/').pop()?.replace('.svg', '') || 'unknown';
          symbolId = `symbol_${symbolName}`;
          
          if (!symbolMap.has(symbolId)) {
            symbolMap.set(symbolId, button.symbolPath);
            assets.symbols?.push({
              id: symbolId,
              set: 'mulberry',
              ref: symbolName,
              file: button.symbolPath,
              alt_text: button.label || symbolName
            });
          }
        }
        
        const cell: AacCell = {
          id: cellId,
          row: button.row + 1, // Master AAC uses 1-based indexing
          col: button.col + 1,
          label: button.label || '',
          speak: button.spokenText || button.label || '',
          symbol_id: symbolId,
          style: {
            bg: button.color || '#3B82F6',
            fg: '#FFFFFF'
          },
          actions: this.convertActions(button.action)
        };
        
        cells.push(cell);
      });
      
      // Convert video players
      (page.videoPlayers || []).forEach((videoPlayer, videoIndex) => {
        const cellId = `video_cell_${pageIndex}_${videoIndex}`;
        const videoId = `video_${videoPlayer.videoId}`;
        
        // Add video asset
        if (!videoMap.has(videoId)) {
          videoMap.set(videoId, videoPlayer.videoId);
          assets.videos?.push({
            id: videoId,
            url: `https://youtube.com/watch?v=${videoPlayer.videoId}`,
            license: 'youtube'
          });
        }
        
        const cell: AacCell = {
          id: cellId,
          row: videoPlayer.row + 1,
          col: videoPlayer.col + 1,
          row_span: videoPlayer.rowSpan,
          col_span: videoPlayer.colSpan,
          label: videoPlayer.title || 'Video Player',
          speak: `Play video: ${videoPlayer.title}`,
          video_id: videoId,
          style: {
            bg: '#1F2937',
            fg: '#FFFFFF'
          },
          actions: [{
            type: 'play_video',
            video_id: videoId
          }]
        };
        
        cells.push(cell);
      });
      
      return {
        id: page.id || `page_${pageIndex}`,
        name: page.name || `Page ${pageIndex + 1}`,
        layout: {
          rows: board.grid.rows,
          cols: board.grid.cols,
          gutter: 2,
          theme: {
            background: '#FFFFFF',
            default_cell_color: '#F3F4F6',
            font_family: 'Arial',
            font_size_pt: 16
          }
        },
        cells
      };
    });
    
    return {
      meta: {
        version: '1.0',
        title: board.name,
        description: `Generated by SyntAACx`,
        locale: 'en-US',
        authors: ['SyntAACx'],
        targets: {
          grid3: true,
          tdsnap: true,
          openboard_obz: false
        }
      },
      assets,
      boards: aacBoards
    };
  }
  
  private static convertActions(action?: ActionIR): AacAction[] {
    if (!action) return [];
    
    switch (action.type) {
      case 'speak':
        return [{
          type: 'speak',
          text: action.text || ''
        }];
        
      case 'navigate':
        return [{
          type: 'navigate',
          target_board_id: action.toPageId || ''
        }];
        
      case 'back':
        return [{
          type: 'back'
        }];
        
      case 'link':
        return [{
          type: 'navigate',
          target_board_id: action.toBoardId || ''
        }];
        
      case 'youtube':
        return [{
          type: 'open_url',
          url: `https://youtube.com/watch?v=${action.videoId}`
        }];
        
      default:
        return [{
          type: 'speak',
          text: 'Button'
        }];
    }
  }
}