/**
 * Emoji → Grid3 Widgit Symbol Mapping Library
 *
 * Maps Unicode emoji characters to Grid3-compatible Widgit Rebus symbol paths.
 * Grid3 uses the format: [widgit]widgit rebus\{first_letter}\{concept}.emf
 *
 * When Grid3 can't find the exact file, it falls back to built-in symbol search
 * using the <Caption> text, so semantic accuracy matters more than exact filenames.
 *
 * Usage:
 *   import { emojiToGrid3Symbol, resolveGrid3Symbol } from './emoji-to-grid3';
 *   const path = emojiToGrid3Symbol('😊');  // → '[widgit]widgit rebus\\h\\happy.emf'
 *   const path = resolveGrid3Symbol('😊', 'Happy');  // tries emoji first, then label
 */

// ---------------------------------------------------------------------------
// Core mapping: emoji → Widgit concept name
// ---------------------------------------------------------------------------

/**
 * Maps emoji codepoints to Widgit Rebus concept names.
 * The concept name is used to build the symbol path:
 *   [widgit]widgit rebus\{first_letter}\{concept}.emf
 */
const EMOJI_TO_CONCEPT: Record<string, string> = {
  // =========================================================================
  // EMOTIONS & FEELINGS
  // =========================================================================
  '😊': 'happy',
  '😃': 'happy',
  '😄': 'happy',
  '😁': 'happy',
  '🙂': 'happy',
  '😀': 'happy',
  '☺️': 'happy',
  '☺': 'happy',
  '🥰': 'love',
  '😍': 'love',
  '❤️': 'love',
  '❤': 'love',
  '💕': 'love',
  '💖': 'love',
  '💗': 'love',
  '💓': 'love',
  '💛': 'love',
  '💙': 'love',
  '💚': 'love',
  '🧡': 'love',
  '💜': 'love',
  '🤍': 'love',
  '🖤': 'love',
  '🩷': 'love',
  '🩵': 'love',
  '🩶': 'love',
  '😢': 'sad',
  '😭': 'cry',
  '😿': 'sad',
  '☹️': 'sad',
  '☹': 'sad',
  '🥺': 'sad',
  '😞': 'sad',
  '😔': 'sad',
  '😟': 'worried',
  '😰': 'worried',
  '😥': 'worried',
  '😨': 'scared',
  '😱': 'scared',
  '🫣': 'scared',
  '😠': 'angry',
  '😡': 'angry',
  '🤬': 'angry',
  '😤': 'angry',
  '👿': 'angry',
  '😐': 'calm',
  '😑': 'calm',
  '😌': 'calm',
  '🧘': 'calm',
  '😮': 'surprised',
  '😲': 'surprised',
  '🤯': 'surprised',
  '😳': 'surprised',
  '😵': 'confused',
  '😕': 'confused',
  '🤔': 'confused',
  '😖': 'confused',
  '🤩': 'excited',
  '🥳': 'excited',
  '🎉': 'excited',
  '🎊': 'excited',
  '😴': 'tired',
  '🥱': 'tired',
  '😪': 'tired',
  '💤': 'sleep',
  '🛌': 'sleep',
  '😎': 'cool',
  '🤒': 'ill',
  '🤕': 'ill',
  '🤢': 'ill',
  '🤮': 'ill',
  '🤧': 'ill',
  '🥵': 'hot',
  '🥶': 'cold',
  '😬': 'nervous',
  '🫤': 'unsure',
  '😒': 'bored',
  '🫠': 'bored',
  '😇': 'kind',
  '🤗': 'hug',
  '😘': 'kiss',
  '💋': 'kiss',
  '🤞': 'hope',
  '😶': 'quiet',
  '🤫': 'quiet',
  '🤐': 'quiet',

  // =========================================================================
  // PEOPLE & FAMILY
  // =========================================================================
  '👩': 'woman',
  '👨': 'man',
  '👧': 'girl',
  '👦': 'boy',
  '👶': 'baby',
  '🧒': 'child',
  '👤': 'person',
  '👥': 'people',
  '👫': 'people',
  '👬': 'people',
  '👭': 'people',
  '👪': 'family',
  '👨‍👩‍👧': 'family',
  '👨‍👩‍👦': 'family',
  '👨‍👩‍👧‍👦': 'family',
  '👩‍👦': 'mum',
  '👩‍👧': 'mum',
  '🤱': 'mum',
  '👨‍👦': 'dad',
  '👨‍👧': 'dad',
  '🧓': 'grandparent',
  '👵': 'grandmother',
  '👴': 'grandfather',
  '👸': 'princess',
  '🤴': 'prince',
  '🧑‍🏫': 'teacher',
  '👩‍🏫': 'teacher',
  '👨‍🏫': 'teacher',
  '🧑‍⚕️': 'doctor',
  '👩‍⚕️': 'doctor',
  '👨‍⚕️': 'doctor',
  '👋': 'hello',
  '🤝': 'friend',
  '🫶': 'love',

  // =========================================================================
  // FOOD & DRINK
  // =========================================================================
  '🍽️': 'food',
  '🍽': 'food',
  '🍕': 'pizza',
  '🍔': 'hamburger',
  '🌭': 'sausage',
  '🥪': 'sandwich',
  '🌮': 'food',
  '🌯': 'food',
  '🍟': 'chips',
  '🥗': 'salad',
  '🥘': 'food',
  '🍝': 'pasta',
  '🍜': 'soup',
  '🍲': 'soup',
  '🍛': 'food',
  '🍣': 'fish',
  '🥩': 'meat',
  '🍗': 'chicken',
  '🍖': 'meat',
  '🥚': 'egg',
  '🍞': 'bread',
  '🥐': 'bread',
  '🥖': 'bread',
  '🧀': 'cheese',
  '🥜': 'nuts',
  '🥕': 'carrot',
  '🥦': 'vegetables',
  '🥬': 'vegetables',
  '🥒': 'vegetables',
  '🌽': 'corn',
  '🍅': 'tomato',
  '🥔': 'potato',
  '🧅': 'onion',
  '🍎': 'apple',
  '🍏': 'apple',
  '🍌': 'banana',
  '🍊': 'orange',
  '🍇': 'grapes',
  '🍓': 'strawberry',
  '🫐': 'fruit',
  '🍑': 'peach',
  '🍐': 'pear',
  '🍉': 'melon',
  '🥝': 'fruit',
  '🥭': 'fruit',
  '🍍': 'pineapple',
  '🥥': 'coconut',
  '🍦': 'ice cream',
  '🍧': 'ice cream',
  '🍨': 'ice cream',
  '🍩': 'cake',
  '🍪': 'biscuit',
  '🎂': 'cake',
  '🍰': 'cake',
  '🧁': 'cake',
  '🍫': 'chocolate',
  '🍬': 'sweet',
  '🍭': 'sweet',
  '🥤': 'drink',
  '🧃': 'juice',
  '🧊': 'cold',
  '☕': 'drink',
  '🍵': 'drink',
  '🥛': 'milk',
  '🍶': 'drink',
  '🍼': 'bottle',
  '💧': 'water',
  '🚰': 'water',
  '🧋': 'drink',

  // =========================================================================
  // ACTIONS & VERBS
  // =========================================================================
  '🗣️': 'speak',
  '🗣': 'speak',
  '💬': 'speak',
  '🗨️': 'speak',
  '💭': 'think',
  '🧠': 'think',
  '👀': 'look',
  '👁️': 'look',
  '👁': 'look',
  '👂': 'listen',
  '🦻': 'listen',
  '✋': 'stop',
  '🛑': 'stop',
  '⛔': 'stop',
  '🖐️': 'stop',
  '🖐': 'stop',
  '🚫': 'no',
  '❌': 'no',
  '⭕': 'no',
  '✅': 'yes',
  '✔️': 'yes',
  '✔': 'yes',
  '👍': 'yes',
  '👎': 'no',
  '🆗': 'yes',
  '👆': 'point',
  '👇': 'point',
  '👈': 'point',
  '👉': 'point',
  '☝️': 'point',
  '☝': 'point',
  '🤚': 'wait',
  '✊': 'strong',
  '💪': 'strong',
  '👏': 'well done',
  '🙌': 'well done',
  '⭐': 'well done',
  '🌟': 'well done',
  '🏆': 'well done',
  '🥇': 'winner',
  '🎖️': 'well done',
  '🏅': 'well done',
  '🏃': 'run',
  '🏃‍♂️': 'run',
  '🏃‍♀️': 'run',
  '🚶': 'walk',
  '🚶‍♂️': 'walk',
  '🚶‍♀️': 'walk',
  '🧍': 'stand',
  '🧎': 'sit',
  '💃': 'dance',
  '🕺': 'dance',
  '🤸': 'jump',
  '🏊': 'swim',
  '🏊‍♂️': 'swim',
  '🏊‍♀️': 'swim',
  '🧗': 'climb',
  '🚴': 'ride',
  '🚴‍♂️': 'ride',
  '🚴‍♀️': 'ride',
  '✍️': 'write',
  '✍': 'write',
  '✏️': 'write',
  '✏': 'write',
  '📝': 'write',
  '📖': 'read',
  '📚': 'read',
  '📕': 'book',
  '📗': 'book',
  '📘': 'book',
  '📙': 'book',
  '🎵': 'music',
  '🎶': 'music',
  '🎤': 'sing',
  '🎸': 'music',
  '🎹': 'music',
  '🥁': 'music',
  '🎺': 'music',
  '🎻': 'music',
  '🎨': 'paint',
  '🖌️': 'paint',
  '🖌': 'paint',
  '🖍️': 'draw',
  '🖍': 'draw',
  '✂️': 'cut',
  '✂': 'cut',
  '🔨': 'build',
  '🛠️': 'build',
  '🛠': 'build',
  '🧩': 'puzzle',
  '🎮': 'play',
  '🕹️': 'play',
  '🕹': 'play',
  '🎲': 'play',
  '🃏': 'play',
  '🎯': 'play',
  '⚽': 'football',
  '🏀': 'ball',
  '🏈': 'ball',
  '⚾': 'ball',
  '🎾': 'ball',
  '🏐': 'ball',
  '🏓': 'play',
  '🏸': 'play',
  '🎳': 'play',
  '🛝': 'play',
  '🛷': 'play',
  '⛷️': 'play',
  '🤿': 'swim',
  '🧹': 'clean',
  '🧺': 'wash',
  '🧼': 'wash',
  '🛁': 'bath',
  '🚿': 'wash',
  '🪥': 'brush teeth',
  '🪮': 'brush',
  '👗': 'dress',
  '👕': 'get dressed',
  '👖': 'get dressed',
  '🧥': 'coat',
  '👟': 'shoes',
  '👞': 'shoes',
  '🥾': 'shoes',
  '👒': 'hat',
  '🧢': 'hat',
  '🎒': 'bag',
  '👓': 'glasses',
  '🛒': 'shopping',
  '💰': 'money',
  '💵': 'money',
  '🪙': 'money',

  // =========================================================================
  // PLACES & BUILDINGS
  // =========================================================================
  '🏠': 'home',
  '🏡': 'home',
  '🏘️': 'home',
  '🏘': 'home',
  '🏫': 'school',
  '🎓': 'school',
  '🏥': 'hospital',
  '🏪': 'shop',
  '🏬': 'shop',
  '🛍️': 'shopping',
  '🛍': 'shopping',
  '⛪': 'church',
  '🕌': 'mosque',
  '🕍': 'synagogue',
  '🏛️': 'building',
  '🏛': 'building',
  '🏢': 'building',
  '🏰': 'castle',
  '🏖️': 'beach',
  '🏖': 'beach',
  '🏞️': 'park',
  '🏞': 'park',
  '🌳': 'tree',
  '🌲': 'tree',
  '🌿': 'garden',
  '🌻': 'garden',
  '🌺': 'flower',
  '💐': 'flower',
  '🌹': 'flower',
  '🌷': 'flower',
  '🌸': 'flower',
  '🌊': 'sea',
  '🏔️': 'mountain',
  '🏔': 'mountain',
  '⛰️': 'mountain',
  '⛰': 'mountain',
  '🌍': 'world',
  '🌎': 'world',
  '🌏': 'world',
  '🗺️': 'map',

  // =========================================================================
  // TRANSPORT
  // =========================================================================
  '🚗': 'car',
  '🚙': 'car',
  '🏎️': 'car',
  '🏎': 'car',
  '🚌': 'bus',
  '🚍': 'bus',
  '🚎': 'bus',
  '🚐': 'bus',
  '🚑': 'ambulance',
  '🚒': 'fire engine',
  '🚓': 'police car',
  '🚕': 'taxi',
  '🚜': 'tractor',
  '🚛': 'lorry',
  '🚚': 'lorry',
  '🚲': 'bicycle',
  '🛴': 'scooter',
  '🛵': 'scooter',
  '🏍️': 'motorbike',
  '🏍': 'motorbike',
  '🚂': 'train',
  '🚃': 'train',
  '🚄': 'train',
  '🚅': 'train',
  '🚆': 'train',
  '🚇': 'train',
  '✈️': 'aeroplane',
  '✈': 'aeroplane',
  '🛩️': 'aeroplane',
  '🛩': 'aeroplane',
  '🚀': 'rocket',
  '🛸': 'spaceship',
  '🚁': 'helicopter',
  '⛵': 'boat',
  '🚢': 'boat',
  '🛥️': 'boat',
  '🛥': 'boat',
  '🚤': 'boat',
  '♿': 'wheelchair',
  '🦽': 'wheelchair',
  '🦼': 'wheelchair',

  // =========================================================================
  // ANIMALS
  // =========================================================================
  '🐶': 'dog',
  '🐕': 'dog',
  '🦮': 'dog',
  '🐕‍🦺': 'dog',
  '🐩': 'dog',
  '🐱': 'cat',
  '🐈': 'cat',
  '🐈‍⬛': 'cat',
  '🐴': 'horse',
  '🐎': 'horse',
  '🦄': 'unicorn',
  '🐮': 'cow',
  '🐄': 'cow',
  '🐷': 'pig',
  '🐖': 'pig',
  '🐑': 'sheep',
  '🐏': 'sheep',
  '🐐': 'goat',
  '🐔': 'chicken',
  '🐓': 'chicken',
  '🐣': 'chick',
  '🐤': 'chick',
  '🐥': 'chick',
  '🐦': 'bird',
  '🐧': 'penguin',
  '🦅': 'eagle',
  '🦆': 'duck',
  '🦉': 'owl',
  '🦜': 'parrot',
  '🐸': 'frog',
  '🐍': 'snake',
  '🐢': 'turtle',
  '🦎': 'lizard',
  '🐊': 'crocodile',
  '🐟': 'fish',
  '🐠': 'fish',
  '🐡': 'fish',
  '🐬': 'dolphin',
  '🐳': 'whale',
  '🐋': 'whale',
  '🦈': 'shark',
  '🐙': 'octopus',
  '🦀': 'crab',
  '🦐': 'prawn',
  '🐛': 'caterpillar',
  '🦋': 'butterfly',
  '🐝': 'bee',
  '🐞': 'ladybird',
  '🕷️': 'spider',
  '🕷': 'spider',
  '🐜': 'ant',
  '🐌': 'snail',
  '🐇': 'rabbit',
  '🐰': 'rabbit',
  '🐿️': 'squirrel',
  '🐿': 'squirrel',
  '🦔': 'hedgehog',
  '🐻': 'bear',
  '🐼': 'panda',
  '🐨': 'koala',
  '🦁': 'lion',
  '🐯': 'tiger',
  '🐘': 'elephant',
  '🦒': 'giraffe',
  '🦓': 'zebra',
  '🦏': 'rhinoceros',
  '🦛': 'hippopotamus',
  '🐒': 'monkey',
  '🐵': 'monkey',
  '🦍': 'gorilla',
  '🐻‍❄️': 'polar bear',
  '🐫': 'camel',
  '🐪': 'camel',
  '🦘': 'kangaroo',
  '🦩': 'flamingo',
  '🦚': 'peacock',
  '🐺': 'wolf',
  '🦊': 'fox',
  '🦌': 'deer',
  '🐁': 'mouse',
  '🐭': 'mouse',
  '🐹': 'hamster',

  // =========================================================================
  // NATURE & WEATHER
  // =========================================================================
  '☀️': 'sun',
  '☀': 'sun',
  '🌤️': 'sun',
  '🌤': 'sun',
  '⛅': 'cloudy',
  '☁️': 'cloud',
  '☁': 'cloud',
  '🌧️': 'rain',
  '🌧': 'rain',
  '🌦️': 'rain',
  '🌦': 'rain',
  '⛈️': 'storm',
  '⛈': 'storm',
  '🌩️': 'storm',
  '🌩': 'storm',
  '⚡': 'lightning',
  '🌈': 'rainbow',
  '❄️': 'snow',
  '❄': 'snow',
  '⛄': 'snowman',
  '☃️': 'snowman',
  '☃': 'snowman',
  '🌬️': 'wind',
  '🌬': 'wind',
  '💨': 'wind',
  '🌡️': 'temperature',
  '🌡': 'temperature',
  '🔥': 'fire',
  '🌙': 'night',
  '🌛': 'night',
  '🌜': 'night',
  '💫': 'star',

  // =========================================================================
  // OBJECTS & TECHNOLOGY
  // =========================================================================
  '📱': 'phone',
  '📲': 'phone',
  '☎️': 'telephone',
  '☎': 'telephone',
  '💻': 'computer',
  '🖥️': 'computer',
  '🖥': 'computer',
  '⌨️': 'keyboard',
  '⌨': 'keyboard',
  '🖱️': 'computer',
  '🖱': 'computer',
  '🖨️': 'printer',
  '🖨': 'printer',
  '📺': 'tv',
  '📻': 'radio',
  '🔊': 'loud',
  '🔉': 'sound',
  '🔈': 'quiet',
  '🔇': 'quiet',
  '📷': 'camera',
  '📸': 'camera',
  '🎥': 'video',
  '📹': 'video',
  '🎬': 'film',
  '📀': 'dvd',
  '💡': 'light',
  '🔦': 'light',
  '🕯️': 'candle',
  '🕯': 'candle',
  '🔑': 'key',
  '🗝️': 'key',
  '🗝': 'key',
  '🔒': 'lock',
  '🔓': 'open',
  '🚪': 'door',
  '🪟': 'window',
  '🛏️': 'bed',
  '🛏': 'bed',
  '🛋️': 'sofa',
  '🛋': 'sofa',
  '🪑': 'chair',
  '🚽': 'toilet',
  '🪞': 'mirror',
  '🧸': 'toy',
  '🪀': 'toy',
  '🎪': 'circus',
  '🎠': 'play',
  '🎡': 'play',
  '🎢': 'play',

  // =========================================================================
  // TIME & SCHEDULING
  // =========================================================================
  '⏰': 'time',
  '🕐': 'time',
  '🕑': 'time',
  '🕒': 'time',
  '🕓': 'time',
  '🕔': 'time',
  '🕕': 'time',
  '🕖': 'time',
  '🕗': 'time',
  '🕘': 'time',
  '🕙': 'time',
  '🕚': 'time',
  '🕛': 'time',
  '⏳': 'wait',
  '⌛': 'wait',
  '📅': 'calendar',
  '📆': 'calendar',
  '🌅': 'morning',
  '🌄': 'morning',
  '🌇': 'evening',
  '🌆': 'evening',
  '🌃': 'night',
  '🌉': 'night',

  // =========================================================================
  // COMMUNICATION & SOCIAL
  // =========================================================================
  '🙏': 'please',
  '🙇': 'thank you',
  '🤙': 'telephone',
  '🫡': 'hello',
  '🫱': 'give',
  '🫴': 'give',
  '🤲': 'give',
  '🤜': 'hit',
  '🤛': 'hit',
  '👊': 'hit',
  '🖖': 'hello',
  '✌️': 'peace',
  '✌': 'peace',
  '🤟': 'love',
  '🫰': 'money',
  '🤌': 'what',
  '🤏': 'small',
  '👌': 'good',

  // =========================================================================
  // BODY & HEALTH
  // =========================================================================
  '🦷': 'tooth',
  '👅': 'tongue',
  '👃': 'nose',
  '👄': 'mouth',
  '🦴': 'bone',
  '🩹': 'hurt',
  '💊': 'medicine',
  '🩺': 'doctor',
  '🩻': 'doctor',
  '🩼': 'crutch',
  '💉': 'injection',
  '😷': 'ill',

  // =========================================================================
  // ABSTRACT / CONCEPTS
  // =========================================================================
  '❓': 'question',
  '❔': 'question',
  '❗': 'important',
  '❕': 'important',
  '⚠️': 'careful',
  '⚠': 'careful',
  '💯': 'well done',
  '🔢': 'number',
  '🔤': 'letter',
  '🔠': 'letter',
  '🔡': 'letter',
  '➕': 'add',
  '➖': 'take away',
  '✖️': 'multiply',
  '✖': 'multiply',
  '➗': 'divide',
  '♻️': 'recycle',
  '♻': 'recycle',
  '🔄': 'again',
  '🔁': 'again',
  '🔂': 'again',
  '⬆️': 'up',
  '⬆': 'up',
  '⬇️': 'down',
  '⬇': 'down',
  '⬅️': 'left',
  '⬅': 'left',
  '➡️': 'right',
  '➡': 'right',
  '↩️': 'back',
  '↩': 'back',
  '🔀': 'change',
  '🆕': 'new',
  '🆒': 'cool',
  '🆓': 'free',
  '🔝': 'top',
  '🔚': 'finish',
  '🔜': 'soon',
  '🔙': 'back',
  '🔃': 'turn',
  '🎁': 'present',
  '🎀': 'present',
  '🏷️': 'label',
  '🏷': 'label',
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Convert a Widgit concept name to a Grid3-compatible symbol path.
 * Uses the convention: [widgit]widgit rebus\{first_letter}\{concept}.emf
 */
export function conceptToGrid3Path(concept: string): string {
  const clean = concept.toLowerCase().trim();
  if (!clean) return '[widgit]widgit rebus\\b\\button.emf';
  const firstLetter = clean.charAt(0);
  return `[widgit]widgit rebus\\${firstLetter}\\${clean}.emf`;
}

/**
 * Look up a Grid3 Widgit symbol path for a single emoji character.
 * Returns the symbol path or null if no mapping exists.
 */
export function emojiToGrid3Symbol(emoji: string): string | null {
  // Normalize: strip variation selectors (VS15 text, VS16 emoji)
  const normalized = emoji.replace(/[\uFE0E\uFE0F]/g, '').trim();

  const concept = EMOJI_TO_CONCEPT[normalized] || EMOJI_TO_CONCEPT[emoji];
  if (!concept) return null;
  return conceptToGrid3Path(concept);
}

/**
 * Look up the Widgit concept name for an emoji.
 * Returns the concept or null.
 */
export function emojiToConcept(emoji: string): string | null {
  const normalized = emoji.replace(/[\uFE0E\uFE0F]/g, '').trim();
  return EMOJI_TO_CONCEPT[normalized] || EMOJI_TO_CONCEPT[emoji] || null;
}

/**
 * Resolve a Grid3 symbol path from an emoji iconRef and/or a label string.
 * Tries emoji first (most specific), then falls back to label-based lookup.
 *
 * @param iconRef - Emoji character from the button's iconRef field
 * @param label   - Button label text (used as fallback)
 * @returns Grid3 Widgit symbol path
 */
export function resolveGrid3Symbol(iconRef: string | undefined, label: string): string {
  // 1. Try emoji lookup
  if (iconRef) {
    const fromEmoji = emojiToGrid3Symbol(iconRef);
    if (fromEmoji) return fromEmoji;
  }

  // 2. Fall back to label-based path (the existing approach)
  const clean = label.toLowerCase().trim();
  if (!clean) return '[widgit]widgit rebus\\b\\button.emf';
  const firstLetter = clean.charAt(0);
  return `[widgit]widgit rebus\\${firstLetter}\\${clean}.emf`;
}

/**
 * Check if a string is an emoji (starts with a non-ASCII character).
 */
export function isEmoji(str: string): boolean {
  if (!str) return false;
  const code = str.codePointAt(0);
  return code !== undefined && code > 0x7F;
}
