/**
 * Guards the COMMITTED Dollhouse game document (games/dollhouse/src/game.spec.json,
 * regenerated by `npm run sync:game-engine -- dollhouse`).
 *
 * The snapshot is allowed to drift from the live world-lab preset — that's the
 * point of vendoring — so this does NOT compare against the preset. It asserts
 * the committed document is one the engine accepts and still describes the
 * dollhouse shape the game was designed around (focused house, defined family).
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { parseGameSettings } from "@shared/world-engine/kernel/manifest";

const specPath = join(process.cwd(), "games", "dollhouse", "src", "game.spec.json");

describe("dollhouse game spec", () => {
  const doc = JSON.parse(readFileSync(specPath, "utf8"));

  it("is an aivota-world document the engine accepts", () => {
    expect(doc.engine).toBe("aivota-world");
    expect(doc.engineVersion).toBe(1);
    const game = parseGameSettings(doc.game, "game");
    expect(game.scope).toBe("town");
  });

  it("keeps the dollhouse shape: spirit avatar watching a focused house", () => {
    expect(doc.game.avatar).toBe("spirit");
    expect(doc.game.initial_focus?.type).toBe("house");
  });

  it("defines the family exhaustively so the town can't add strangers to the house", () => {
    const creatures = doc.game.entities?.creatures;
    expect(creatures?.mode).toBe("all");
    expect(creatures?.list?.length).toBeGreaterThan(0);
    for (const c of creatures.list) expect(typeof c.name).toBe("string");
  });
});
