// capacitor.config.ts
//
// The iPad (iPadOS) shell for the AAC client. Wraps the SAME Vite bundle that
// electron-builder packages for Windows — see electron-builder.yml, which is
// this file's counterpart. Nothing app-specific lives in the native project;
// it is a WKWebView pointed at `webDir`.
//
// Why Capacitor and not Electron: Electron cannot target iPadOS at all (Apple
// forbids third-party JS engines/JIT, and Electron needs Chromium + Node +
// child processes). Capacitor is the closest architectural analogue — the web
// bundle is unchanged and native access goes through a plugin bridge instead
// of the Electron preload. See client-aac/src/lib/platform/ for the
// host-capability layer that keeps feature code from caring which shell it is.
//
// The iOS native project (`ios/`) is NOT committed — it is generated by
// `npx cap add ios` on a macOS runner during release (see
// .github/workflows/release-aac-ios.yml). Generating it fresh each build keeps
// a ~200-file Xcode project out of the repo; everything we customize about it
// is expressed here or in scripts/ios-configure.mjs.

import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  // Matches electron-builder.yml's appId so the two shells share one identity
  // across stores and telemetry. On iOS this is the bundle identifier and must
  // match the App ID registered in the Apple Developer portal.
  appId: "com.aivota.aac",
  appName: "Aivota AAC",

  // The Vite output, identical to what electron-builder ships as
  // dist/public-aac. Built with NATIVE_BUILD=1 so `base` is relative — an
  // absolute /aac/ base would 404 under the capacitor:// scheme.
  webDir: "dist/public-aac",

  ios: {
    // capacitor://localhost. Registered server-side as a native app origin
    // (see NATIVE_APP_ORIGINS in server/middleware/security.ts) — without that
    // every API call fails CORS.
    scheme: "capacitor",
    // The AAC UI paints its own background; the default white flash between
    // splash and first paint reads as a glitch on a communication device.
    backgroundColor: "#000000",
    // Never bounce-scroll the shell. The board is a fixed-layout surface and
    // rubber-banding under a dwell/touch target moves it out from under the
    // student mid-selection.
    scrollEnabled: false,
    // Keep the WKWebView inline for media playback; the AAC client renders its
    // own video surfaces and must not have iOS hijack them fullscreen.
    limitsNavigationsToAppBoundDomains: false,
  },

  plugins: {
    CapacitorUpdater: {
      // OTA bundle updates are wired but DELIBERATELY INERT for now:
      // autoUpdate false means the plugin loads and reports version info but
      // never downloads or swaps a bundle on its own.
      //
      // Rationale: an OTA updater that misbehaves can leave the app stuck on a
      // broken bundle, and recovering that requires a device we do not have.
      // The shell gets verified on a real iPad first; then this flips to true
      // and `updateUrl` points at the feed. Until then iPad updates ship
      // through TestFlight/App Store like any other binary.
      //
      // See client-aac/src/lib/platform/update.ts for the consuming side.
      autoUpdate: false,
      // Tell the plugin the app is healthy itself rather than requiring the
      // JS to call notifyAppReady() — while autoUpdate is off there is no
      // rollback path for it to guard, and a missed call would be a silent
      // revert loop once we do enable it.
      resetWhenUpdate: false,
    },
  },
};

export default config;
