-- =============================================================================
-- Data backfill: move legacy biometric fields into biometric_data rows
-- =============================================================================
-- Runs BEFORE the drops so no data is lost. Each DO block iterates rows that
-- have legacy biometric fields populated but no biometric_data_id yet, creates
-- a biometric_data row, and links the parent row to it.

-- Users: face + voice embeddings
DO $$
DECLARE r RECORD;
DECLARE new_bd_id varchar;
BEGIN
  FOR r IN
    SELECT id, face_embedding, voice_embedding
    FROM users
    WHERE (face_embedding IS NOT NULL OR voice_embedding IS NOT NULL)
      AND biometric_data_id IS NULL
  LOOP
    INSERT INTO biometric_data (face_embedding, voice_embedding)
    VALUES (r.face_embedding, r.voice_embedding)
    RETURNING id INTO new_bd_id;
    UPDATE users SET biometric_data_id = new_bd_id WHERE id = r.id;
  END LOOP;
END $$;
--> statement-breakpoint

-- Students: face + voice embeddings
DO $$
DECLARE r RECORD;
DECLARE new_bd_id varchar;
BEGIN
  FOR r IN
    SELECT id, face_embedding, voice_embedding
    FROM students
    WHERE (face_embedding IS NOT NULL OR voice_embedding IS NOT NULL)
      AND biometric_data_id IS NULL
  LOOP
    INSERT INTO biometric_data (face_embedding, voice_embedding)
    VALUES (r.face_embedding, r.voice_embedding)
    RETURNING id INTO new_bd_id;
    UPDATE students SET biometric_data_id = new_bd_id WHERE id = r.id;
  END LOOP;
END $$;
--> statement-breakpoint

-- Student contacts: embeddings + physical descriptors (description →
-- physical_description; face_image_data is dropped outright — it was unused
-- base64 legacy; new uploads write to biometric_data.face_image_url via S3).
DO $$
DECLARE r RECORD;
DECLARE new_bd_id varchar;
BEGIN
  FOR r IN
    SELECT id, face_embedding, voice_embedding, hair_color, estimated_age,
           estimated_sex, description, face_image_quality
    FROM student_contacts
    WHERE (face_embedding IS NOT NULL
           OR voice_embedding IS NOT NULL
           OR hair_color IS NOT NULL
           OR estimated_age IS NOT NULL
           OR estimated_sex IS NOT NULL
           OR description IS NOT NULL
           OR face_image_quality IS NOT NULL)
      AND biometric_data_id IS NULL
  LOOP
    INSERT INTO biometric_data (
      face_embedding, voice_embedding,
      hair_color, estimated_age, estimated_sex,
      physical_description, face_image_quality
    )
    VALUES (
      r.face_embedding, r.voice_embedding,
      r.hair_color, r.estimated_age, r.estimated_sex,
      r.description, r.face_image_quality
    )
    RETURNING id INTO new_bd_id;
    UPDATE student_contacts SET biometric_data_id = new_bd_id WHERE id = r.id;
  END LOOP;
END $$;
--> statement-breakpoint

-- =============================================================================
-- Drops (generated by drizzle-kit)
-- =============================================================================
ALTER TABLE "team_members" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
-- DROP TABLE CASCADE also drops the services_provider_id_team_members_id_fk
-- constraint, so we don't explicitly DROP CONSTRAINT afterwards.
DROP TABLE "team_members" CASCADE;--> statement-breakpoint
ALTER TABLE "services" DROP COLUMN "provider_id";--> statement-breakpoint
ALTER TABLE "student_contacts" DROP COLUMN "hair_color";--> statement-breakpoint
ALTER TABLE "student_contacts" DROP COLUMN "estimated_age";--> statement-breakpoint
ALTER TABLE "student_contacts" DROP COLUMN "estimated_sex";--> statement-breakpoint
ALTER TABLE "student_contacts" DROP COLUMN "description";--> statement-breakpoint
ALTER TABLE "student_contacts" DROP COLUMN "face_embedding";--> statement-breakpoint
ALTER TABLE "student_contacts" DROP COLUMN "voice_embedding";--> statement-breakpoint
ALTER TABLE "student_contacts" DROP COLUMN "face_image_data";--> statement-breakpoint
ALTER TABLE "student_contacts" DROP COLUMN "face_image_quality";--> statement-breakpoint
ALTER TABLE "students" DROP COLUMN "face_embedding";--> statement-breakpoint
ALTER TABLE "students" DROP COLUMN "voice_embedding";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "face_embedding";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "voice_embedding";
