// shared/world-engine/creatures/animals-people.ts
//
// Creature-builder blueprints for PEOPLE species — human, human_cute, and the
// animal-people (bear/frog/dog/rabbit) — authored in the seagull-dream lab
// (animals-people.json) and inlined here as a TS module (the root tsconfig has
// no resolveJsonModule, and shared is bundler-agnostic). PURE DATA; species.ts
// registers these by their `name`.
export const ANIMAL_PEOPLE_BLUEPRINTS: Array<Record<string, unknown>> =
[{
  "name": "human",
  "version": 1,
  "spine": {
    "torsoSegments": 6,
    "torsoLengthM": 0.6,
    "girth": 0.2,
    "girthPeak": 0.51,
    "frontTaper": 0.02,
    "rearTaper": 0.255,
    "crossSection": 1.5,
    "profile": [
      {
        "at": 0.18,
        "scale": 1.15
      },
      {
        "at": 0.52,
        "scale": 0.88
      },
      {
        "at": 0.85,
        "scale": 1
      }
    ]
  },
  "neck": {
    "segments": 2,
    "lengthFrac": 0.2,
    "radiusFrac": 0.38,
    "lift": 0.1
  },
  "tail": {
    "segments": 0,
    "lengthFrac": 0.8,
    "radiusFrac": 0.5,
    "droop": 0.5
  },
  "head": {
    "sizeFrac": 1.019,
    "lengthFrac": 1.05,
    "braincaseDome": 0.95,
    "crossSection": 0.88,
    "facePitch": -0.0449999999999999,
    "faceHeight": -0.45,
    "foreheadHeight": 0.28,
    "foreheadLength": 0.22,
    "foreheadSlope": 0.1,
    "beak": 0,
    "snoutLengthFrac": 0.01,
    "snoutSegments": 1,
    "snoutRadiusFrac": 0.2522,
    "muzzleSquash": 0,
    "snoutFlatten": 1.1,
    "snoutCurve": -0.31,
    "mouthOpen": 0.135,
    "jawDepth": 0,
    "jawOffset": -0.03,
    "mouthVertical": 0,
    "noseLengthFrac": 0.27,
    "noseRadiusFrac": 0.201,
    "noseHeight": 0.315,
    "noseSegments": 2,
    "noseDroop": 0.36,
    "eyePairs": 1,
    "eyeSizeFrac": 0.138,
    "eyeAngle": 0.45,
    "eyeHeight": 0.3,
    "eyeBulge": 0,
    "padding": 0.35,
    "cheek": 0.5,
    "jowl": 0.1,
    "brow": 0.12,
    "muzzlePad": 0,
    "lips": 0.805,
    "chin": 0
  },
  "limbGroups": [
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0.88,
      "stationEnd": 0.88,
      "sizePeak": 1,
      "sizeContrast": 0.12,
      "lengthFrac": 1.852,
      "radiusFrac": 0.52,
      "taper": 0.45,
      "membrane": 0,
      "attachHeight": 0.3,
      "restProtraction": 0.26,
      "restLevation": -0.76,
      "restFlexion": 0.24,
      "flexRange": 0.475,
      "legTwist": 0.72,
      "legBalance": -0.03,
      "footLengthFrac": 0.198,
      "stance": 0,
      "ankleRange": 0.705,
      "toeCount": 5,
      "toeLengthFrac": 0.236,
      "toeSpread": 0.25,
      "toeContrast": 0.3,
      "opposition": 0,
      "toeCurl": 0.1
    },
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0,
      "stationEnd": 0,
      "sizePeak": 0.94,
      "sizeContrast": 0.12,
      "lengthFrac": 1.06,
      "radiusFrac": 0.369,
      "taper": 0.5,
      "membrane": 0,
      "attachHeight": 0.565,
      "restProtraction": 0.02,
      "restLevation": -0.71,
      "restFlexion": 0.19,
      "flexRange": 0.885,
      "legTwist": 0,
      "legBalance": 0,
      "footLengthFrac": 0.132,
      "stance": 0.15,
      "ankleRange": 1,
      "toeCount": 4,
      "toeLengthFrac": 0.624,
      "toeSpread": 0.602,
      "toeContrast": 0.21,
      "opposition": 0.7,
      "toeCurl": 0.1
    }
  ],
  "chains": [],
  "membranes": [],
  "growths": [],
  "skin": {
    "baseColor": "#ffffff",
    "bellyColor": "#ffffff",
    "accentColor": "#ffffff"
  },
  "posture": {
    "bodyPitch": 1.362872800004023,
    "bodyHeight": 0.785
  }
},
{
  "version": 1,
  "name": "human_cute",
  "spine": {
    "torsoSegments": 6,
    "torsoLengthM": 0.6,
    "girth": 0.45,
    "girthPeak": 0.51,
    "frontTaper": 0.02,
    "rearTaper": 0.255,
    "crossSection": 1.5,
    "profile": [
      {
        "at": 0.18,
        "scale": 1.15
      },
      {
        "at": 0.52,
        "scale": 0.88
      },
      {
        "at": 0.85,
        "scale": 1
      }
    ]
  },
  "neck": {
    "segments": 2,
    "lengthFrac": 0.2,
    "radiusFrac": 0.38,
    "lift": 0.1
  },
  "tail": {
    "segments": 0,
    "lengthFrac": 0.8,
    "radiusFrac": 0.5,
    "droop": 0.5
  },
  "head": {
    "sizeFrac": 1.019,
    "lengthFrac": 1.05,
    "braincaseDome": 0.95,
    "crossSection": 0.88,
    "facePitch": -0.0449999999999999,
    "faceHeight": -0.45,
    "foreheadHeight": 0.28,
    "foreheadLength": 0.22,
    "foreheadSlope": 0.1,
    "beak": 0,
    "snoutLengthFrac": 0.01,
    "snoutSegments": 1,
    "snoutRadiusFrac": 0.2522,
    "muzzleSquash": 0,
    "snoutFlatten": 1.1,
    "snoutCurve": -0.31,
    "mouthOpen": 0.135,
    "jawDepth": 0,
    "jawOffset": -0.03,
    "mouthVertical": 0,
    "noseLengthFrac": 0.27,
    "noseRadiusFrac": 0.201,
    "noseHeight": 0.315,
    "noseSegments": 2,
    "noseDroop": 0.36,
    "eyePairs": 1,
    "eyeSizeFrac": 0.138,
    "eyeAngle": 0.45,
    "eyeHeight": 0.3,
    "eyeBulge": 0,
    "padding": 0.35,
    "cheek": 0.5,
    "jowl": 0.1,
    "brow": 0.12,
    "muzzlePad": 0,
    "lips": 0.805,
    "chin": 0
  },
  "limbGroups": [
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0.88,
      "stationEnd": 0.88,
      "sizePeak": 1,
      "sizeContrast": 0.12,
      "lengthFrac": 1.852,
      "radiusFrac": 0.52,
      "taper": 0.45,
      "membrane": 0,
      "attachHeight": 0.3,
      "restProtraction": 0.26,
      "restLevation": -0.76,
      "restFlexion": 0.24,
      "flexRange": 0.475,
      "legTwist": 0.72,
      "legBalance": -0.03,
      "footLengthFrac": 0.198,
      "stance": 0,
      "ankleRange": 0.705,
      "toeCount": 5,
      "toeLengthFrac": 0.236,
      "toeSpread": 0.25,
      "toeContrast": 0.3,
      "opposition": 0,
      "toeCurl": 0.1
    },
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0,
      "stationEnd": 0,
      "sizePeak": 0.94,
      "sizeContrast": 0.12,
      "lengthFrac": 1.06,
      "radiusFrac": 0.369,
      "taper": 0.5,
      "membrane": 0,
      "attachHeight": 0.565,
      "restProtraction": 0.02,
      "restLevation": -0.71,
      "restFlexion": 0.19,
      "flexRange": 0.885,
      "legTwist": 0,
      "legBalance": 0,
      "footLengthFrac": 0.132,
      "stance": 0.15,
      "ankleRange": 1,
      "toeCount": 4,
      "toeLengthFrac": 0.624,
      "toeSpread": 0.602,
      "toeContrast": 0.21,
      "opposition": 0.7,
      "toeCurl": 0.1
    }
  ],
  "chains": [],
  "membranes": [],
  "growths": [],
  "skin": {
    "baseColor": "#ffffff",
    "bellyColor": "#ffffff",
    "accentColor": "#ffffff"
  },
  "posture": {
    "bodyPitch": 1.362872800004023,
    "bodyHeight": 0.785
  }
},
{
  "version": 1,
  "name": "bear_person",
  "spine": {
    "torsoSegments": 6,
    "torsoLengthM": 0.6,
    "girth": 0.45,
    "girthPeak": 0.51,
    "frontTaper": 0.02,
    "rearTaper": 0.255,
    "crossSection": 1.5,
    "profile": [
      {
        "at": 0.18,
        "scale": 1.15
      },
      {
        "at": 0.52,
        "scale": 0.88
      },
      {
        "at": 0.85,
        "scale": 1
      }
    ]
  },
  "neck": {
    "segments": 2,
    "lengthFrac": 0.2,
    "radiusFrac": 0.38,
    "lift": 0.1
  },
  "tail": {
    "segments": 0,
    "lengthFrac": 0.8,
    "radiusFrac": 0.5,
    "droop": 0.5
  },
  "head": {
    "sizeFrac": 1.208,
    "lengthFrac": 0.681,
    "braincaseDome": 0.5585,
    "crossSection": 0.679,
    "facePitch": -0.0449999999999999,
    "faceHeight": -0.45,
    "foreheadHeight": 0.28,
    "foreheadLength": 0.4,
    "foreheadSlope": 0.1,
    "beak": 0,
    "snoutLengthFrac": 0.375,
    "snoutSegments": 1,
    "snoutRadiusFrac": 0.244,
    "muzzleSquash": 1,
    "snoutFlatten": 0.823,
    "snoutCurve": 0.06,
    "mouthOpen": 1.14,
    "jawDepth": 0,
    "jawOffset": 0.04,
    "mouthVertical": -0.05,
    "noseLengthFrac": 0.12,
    "noseRadiusFrac": 0.24375,
    "noseHeight": 0,
    "noseSegments": 2,
    "noseDroop": 0.06,
    "eyePairs": 1,
    "eyeSizeFrac": 0.138,
    "eyeAngle": 0.45,
    "eyeHeight": 0.3,
    "eyeBulge": 0,
    "padding": 0.35,
    "cheek": 1,
    "jowl": 0.1,
    "brow": 0.12,
    "muzzlePad": 0,
    "lips": 0.805,
    "chin": 0
  },
  "limbGroups": [
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0.88,
      "stationEnd": 0.88,
      "sizePeak": 1,
      "sizeContrast": 0.12,
      "lengthFrac": 1.852,
      "radiusFrac": 0.6,
      "taper": 0.496,
      "membrane": 0,
      "attachHeight": 0.3,
      "restProtraction": 0.26,
      "restLevation": -0.76,
      "restFlexion": 0.24,
      "flexRange": 0.475,
      "legTwist": 0.72,
      "legBalance": -0.03,
      "footLengthFrac": 0.198,
      "stance": 0,
      "ankleRange": 0.705,
      "toeCount": 5,
      "toeLengthFrac": 0.236,
      "toeSpread": 0.25,
      "toeContrast": 0.3,
      "opposition": 0,
      "toeCurl": 0.1
    },
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0,
      "stationEnd": 0,
      "sizePeak": 0.94,
      "sizeContrast": 0.12,
      "lengthFrac": 1.06,
      "radiusFrac": 0.6,
      "taper": 0.5,
      "membrane": 0,
      "attachHeight": 0.565,
      "restProtraction": 0.02,
      "restLevation": -0.71,
      "restFlexion": 0.19,
      "flexRange": 0.885,
      "legTwist": 0,
      "legBalance": 0,
      "footLengthFrac": 0.132,
      "stance": 0.15,
      "ankleRange": 1,
      "toeCount": 4,
      "toeLengthFrac": 0.624,
      "toeSpread": 0.602,
      "toeContrast": 0.21,
      "opposition": 0.7,
      "toeCurl": 0.1
    }
  ],
  "chains": [],
  "membranes": [],
  "growths": [],
  "skin": {
    "baseColor": "#896e48",
    "bellyColor": "#aa8d50",
    "accentColor": "#000000"
  },
  "posture": {
    "bodyPitch": 1.386,
    "bodyHeight": 0.785
  }
},
{
  "version": 1,
  "name": "frog_person",
  "spine": {
    "torsoSegments": 6,
    "torsoLengthM": 0.6,
    "girth": 0.45,
    "girthPeak": 0.805,
    "frontTaper": 0.02,
    "rearTaper": 0.255,
    "crossSection": 1.5,
    "profile": [
      {
        "at": 0.18,
        "scale": 1.15
      },
      {
        "at": 0.52,
        "scale": 0.88
      },
      {
        "at": 0.85,
        "scale": 1
      }
    ]
  },
  "neck": {
    "segments": 2,
    "lengthFrac": 0.225,
    "radiusFrac": 0.684,
    "lift": -0.365
  },
  "tail": {
    "segments": 0,
    "lengthFrac": 0.8,
    "radiusFrac": 0.5,
    "droop": 0.5
  },
  "head": {
    "sizeFrac": 1.005,
    "lengthFrac": 0.843,
    "braincaseDome": 0.5,
    "crossSection": 1.075,
    "facePitch": -0.0449999999999999,
    "faceHeight": -0.45,
    "foreheadHeight": 0.28,
    "foreheadLength": 0.4,
    "foreheadSlope": 0.1,
    "beak": 0,
    "snoutLengthFrac": 0.325,
    "snoutSegments": 1,
    "snoutRadiusFrac": 0.244,
    "muzzleSquash": 0,
    "snoutFlatten": 2.27425,
    "snoutCurve": 0.02,
    "mouthOpen": 1.1925,
    "jawDepth": 0,
    "jawOffset": 0.04,
    "mouthVertical": -0.09,
    "noseLengthFrac": 0.12,
    "noseRadiusFrac": 0.03,
    "noseHeight": 0,
    "noseSegments": 2,
    "noseDroop": 0.06,
    "eyePairs": 1,
    "eyeSizeFrac": 0.138,
    "eyeAngle": 0.8385,
    "eyeHeight": 0.768,
    "eyeBulge": 0.705,
    "padding": 0.35,
    "cheek": 1,
    "jowl": 0.1,
    "brow": 0.12,
    "muzzlePad": 0,
    "lips": 0.805,
    "chin": 0
  },
  "limbGroups": [
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0.88,
      "stationEnd": 0.88,
      "sizePeak": 1,
      "sizeContrast": 0.12,
      "lengthFrac": 1.984,
      "radiusFrac": 0.6,
      "taper": 0.397,
      "membrane": 0,
      "attachHeight": 0.3,
      "restProtraction": 0.26,
      "restLevation": -0.76,
      "restFlexion": 0.24,
      "flexRange": 0.475,
      "legTwist": 0.72,
      "legBalance": -0.03,
      "footLengthFrac": 0.186,
      "stance": 0,
      "ankleRange": 0.55,
      "toeCount": 5,
      "toeLengthFrac": 0.236,
      "toeSpread": 0.25,
      "toeContrast": 0.3,
      "opposition": 0,
      "toeCurl": 0.1
    },
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0,
      "stationEnd": 0,
      "sizePeak": 0.97,
      "sizeContrast": 0.12,
      "lengthFrac": 1.06,
      "radiusFrac": 0.35775,
      "taper": 0.5,
      "membrane": 0,
      "attachHeight": 0.565,
      "restProtraction": 0.02,
      "restLevation": -0.71,
      "restFlexion": 0.19,
      "flexRange": 0.885,
      "legTwist": 0,
      "legBalance": 0,
      "footLengthFrac": 0.132,
      "stance": 0.15,
      "ankleRange": 1,
      "toeCount": 4,
      "toeLengthFrac": 0.624,
      "toeSpread": 0.602,
      "toeContrast": 0.21,
      "opposition": 0.7,
      "toeCurl": 0.1
    }
  ],
  "chains": [],
  "membranes": [],
  "growths": [],
  "skin": {
    "baseColor": "#53a82e",
    "bellyColor": "#aa8d50",
    "accentColor": "#000000"
  },
  "posture": {
    "bodyPitch": 1.386,
    "bodyHeight": 0.785
  }
},
{
  "version": 1,
  "name": "dog_person",
  "spine": {
    "torsoSegments": 6,
    "torsoLengthM": 0.6,
    "girth": 0.45,
    "girthPeak": 0.51,
    "frontTaper": 0.02,
    "rearTaper": 0.255,
    "crossSection": 1.5,
    "profile": [
      {
        "at": 0.18,
        "scale": 1.15
      },
      {
        "at": 0.52,
        "scale": 0.88
      },
      {
        "at": 0.85,
        "scale": 1
      }
    ]
  },
  "neck": {
    "segments": 2,
    "lengthFrac": 0.2,
    "radiusFrac": 0.38,
    "lift": 0.1
  },
  "tail": {
    "segments": 3,
    "lengthFrac": 0.855,
    "radiusFrac": 0.6295,
    "droop": 1.2
  },
  "head": {
    "sizeFrac": 1.208,
    "lengthFrac": 0.681,
    "braincaseDome": 0.5585,
    "crossSection": 0.418,
    "facePitch": -0.0269999999999999,
    "faceHeight": -0.47,
    "foreheadHeight": 0.275,
    "foreheadLength": 0.02,
    "foreheadSlope": 0.1,
    "beak": 0,
    "snoutLengthFrac": 0.675,
    "snoutSegments": 1,
    "snoutRadiusFrac": 0.244,
    "muzzleSquash": 1,
    "snoutFlatten": 2.1345,
    "snoutCurve": 0.06,
    "mouthOpen": 1.0275,
    "jawDepth": 0,
    "jawOffset": 0.04,
    "mouthVertical": -0.05,
    "noseLengthFrac": 0.12,
    "noseRadiusFrac": 0.24375,
    "noseHeight": 0,
    "noseSegments": 2,
    "noseDroop": 0.06,
    "eyePairs": 1,
    "eyeSizeFrac": 0.138,
    "eyeAngle": 0.45,
    "eyeHeight": 0.3,
    "eyeBulge": 0,
    "padding": 0.35,
    "cheek": 1,
    "jowl": 0.1,
    "brow": 0.12,
    "muzzlePad": 0,
    "lips": 0.805,
    "chin": 0
  },
  "limbGroups": [
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0.88,
      "stationEnd": 0.88,
      "sizePeak": 1,
      "sizeContrast": 0.12,
      "lengthFrac": 1.852,
      "radiusFrac": 0.4518,
      "taper": 0.496,
      "membrane": 0,
      "attachHeight": 0.3,
      "restProtraction": 0.26,
      "restLevation": -0.76,
      "restFlexion": 0.24,
      "flexRange": 0.475,
      "legTwist": 0.72,
      "legBalance": -0.03,
      "footLengthFrac": 0.198,
      "stance": 0,
      "ankleRange": 0.705,
      "toeCount": 5,
      "toeLengthFrac": 0.236,
      "toeSpread": 0.25,
      "toeContrast": 0.3,
      "opposition": 0,
      "toeCurl": 0.1
    },
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0,
      "stationEnd": 0,
      "sizePeak": 0.94,
      "sizeContrast": 0.12,
      "lengthFrac": 1.06,
      "radiusFrac": 0.3435,
      "taper": 0.5,
      "membrane": 0,
      "attachHeight": 0.565,
      "restProtraction": 0.02,
      "restLevation": -0.71,
      "restFlexion": 0.19,
      "flexRange": 0.885,
      "legTwist": 0,
      "legBalance": 0,
      "footLengthFrac": 0.132,
      "stance": 0.15,
      "ankleRange": 1,
      "toeCount": 4,
      "toeLengthFrac": 0.624,
      "toeSpread": 0.602,
      "toeContrast": 0.21,
      "opposition": 0.7,
      "toeCurl": 0.1
    }
  ],
  "chains": [],
  "membranes": [],
  "growths": [],
  "skin": {
    "baseColor": "#896e48",
    "bellyColor": "#aa8d50",
    "accentColor": "#000000"
  },
  "posture": {
    "bodyPitch": 1.386,
    "bodyHeight": 0.785
  }
},
{
  "version": 1,
  "name": "rabbit_person",
  "spine": {
    "torsoSegments": 6,
    "torsoLengthM": 0.6,
    "girth": 0.45,
    "girthPeak": 0.51,
    "frontTaper": 0.02,
    "rearTaper": 0.255,
    "crossSection": 1.5,
    "profile": [
      {
        "at": 0.18,
        "scale": 1.15
      },
      {
        "at": 0.52,
        "scale": 0.88
      },
      {
        "at": 0.85,
        "scale": 1
      }
    ]
  },
  "neck": {
    "segments": 2,
    "lengthFrac": 0.2,
    "radiusFrac": 0.38,
    "lift": 0.1
  },
  "tail": {
    "segments": 3,
    "lengthFrac": 0.855,
    "radiusFrac": 0.6295,
    "droop": 1.2
  },
  "head": {
    "sizeFrac": 1.208,
    "lengthFrac": 0.681,
    "braincaseDome": 0.5585,
    "crossSection": 0.418,
    "facePitch": -0.0269999999999999,
    "faceHeight": -0.47,
    "foreheadHeight": 0.275,
    "foreheadLength": 0.02,
    "foreheadSlope": 0.1,
    "beak": 0,
    "snoutLengthFrac": 0.225,
    "snoutSegments": 1,
    "snoutRadiusFrac": 0.244,
    "muzzleSquash": 1,
    "snoutFlatten": 2.1345,
    "snoutCurve": 0.06,
    "mouthOpen": 0.15,
    "jawDepth": 0,
    "jawOffset": 0.04,
    "mouthVertical": -0.05,
    "noseLengthFrac": 0.12,
    "noseRadiusFrac": 0.24375,
    "noseHeight": 0,
    "noseSegments": 2,
    "noseDroop": 0.06,
    "eyePairs": 1,
    "eyeSizeFrac": 0.138,
    "eyeAngle": 0.45,
    "eyeHeight": 0.3,
    "eyeBulge": 0,
    "padding": 0.35,
    "cheek": 1,
    "jowl": 0.1,
    "brow": 0.12,
    "muzzlePad": 0,
    "lips": 0.805,
    "chin": 0
  },
  "limbGroups": [
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0.88,
      "stationEnd": 0.88,
      "sizePeak": 1,
      "sizeContrast": 0.12,
      "lengthFrac": 1.852,
      "radiusFrac": 0.6,
      "taper": 0.496,
      "membrane": 0,
      "attachHeight": 0.3,
      "restProtraction": 0.26,
      "restLevation": -0.76,
      "restFlexion": 0.24,
      "flexRange": 0.475,
      "legTwist": 0.72,
      "legBalance": -0.03,
      "footLengthFrac": 0.198,
      "stance": 0.73,
      "ankleRange": 0.705,
      "toeCount": 5,
      "toeLengthFrac": 0.236,
      "toeSpread": 0.25,
      "toeContrast": 0.3,
      "opposition": 0,
      "toeCurl": 0.1
    },
    {
      "placement": "bilateral",
      "count": 1,
      "stationStart": 0,
      "stationEnd": 0,
      "sizePeak": 0.94,
      "sizeContrast": 0.12,
      "lengthFrac": 1.06,
      "radiusFrac": 0.29505,
      "taper": 0.5,
      "membrane": 0,
      "attachHeight": 0.565,
      "restProtraction": 0.02,
      "restLevation": -0.71,
      "restFlexion": 0.19,
      "flexRange": 0.885,
      "legTwist": 0,
      "legBalance": 0,
      "footLengthFrac": 0.132,
      "stance": 0.15,
      "ankleRange": 1,
      "toeCount": 4,
      "toeLengthFrac": 0.624,
      "toeSpread": 0.602,
      "toeContrast": 0.21,
      "opposition": 0.7,
      "toeCurl": 0.1
    }
  ],
  "chains": [],
  "membranes": [],
  "growths": [],
  "skin": {
    "baseColor": "#ecebe9",
    "bellyColor": "#d6d6d6",
    "accentColor": "#fdfcfc"
  },
  "posture": {
    "bodyPitch": 1.386,
    "bodyHeight": 0.785
  }
}];
