// server/services/chat/tools/gemini-media-analyzer.ts
// Delegates media analysis (video/image) to Gemini when the primary chat LLM lacks multimodal capabilities

import { GoogleGenAI } from "@google/genai";
import { getFile, getFileStatus, refreshFile, getFileMeta, storeFile } from "./media-file-cache";
import { creditsForModelUsage } from "../cost-helpers";

const ANALYSIS_MODEL = "gemini-2.5-flash";
const IMAGE_CAPABLE_MODEL = "gemini-3-flash-preview";

// Reuse a single client instance
let genaiClient: GoogleGenAI | null = null;
function getClient(): GoogleGenAI {
  if (!genaiClient) {
    genaiClient = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });
  }
  return genaiClient;
}

// Safety settings — disabled for AAC use case (images of children, clinical environments)
const SAFETY_SETTINGS = [
  { category: "HARM_CATEGORY_HARASSMENT" as const, threshold: "OFF" as const },
  { category: "HARM_CATEGORY_HATE_SPEECH" as const, threshold: "OFF" as const },
  { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT" as const, threshold: "OFF" as const },
  { category: "HARM_CATEGORY_DANGEROUS_CONTENT" as const, threshold: "OFF" as const },
];

export interface MediaAnalysisInput {
  /** The instruction/question for Gemini about this media */
  instruction: string;
  /** Conversation context summary so Gemini understands the situation */
  context?: string;
  /** File references: base64 data URLs, or "file:<id>" for server-cached files */
  files: string[];
}

export interface MediaAnalysisResult {
  text: string;
  /** File IDs of any images generated by Gemini (stored in server cache) */
  generatedImageFileIds?: string[];
  /** Credits cost for this analysis (based on Gemini token usage) */
  credits?: number;
}

/**
 * Send files + instruction to Gemini for analysis.
 * Supports images and videos. Can return generated images (e.g. attention heatmaps).
 */
export async function analyzeMedia(input: MediaAnalysisInput): Promise<MediaAnalysisResult> {
  const client = getClient();

  const parts: any[] = [];

  // Add context if provided
  if (input.context) {
    parts.push({ text: `Context: ${input.context}` });
  }

  // Add instruction
  parts.push({ text: input.instruction });

  // Pre-check: ensure all file references are available before calling Gemini
  const expiredFiles: Array<{ fileId: string; filename: string }> = [];
  for (const fileRef of input.files) {
    if (fileRef.startsWith("file:")) {
      const fileId = fileRef.slice(5);
      const status = getFileStatus(fileId);
      if (status === "expired") {
        const meta = getFileMeta(fileId);
        expiredFiles.push({ fileId, filename: meta?.filename || fileId });
      }
    }
  }
  if (expiredFiles.length > 0) {
    return {
      text: "The following files have expired from the server cache. Please wait while the client re-uploads them.",
      filesNeeded: expiredFiles,
    } as any;
  }

  // Process each file — supports base64 data URLs and "file:<id>" references
  for (const fileRef of input.files) {
    let mimeType: string;
    let data: string; // base64
    let buffer: Buffer | undefined;

    if (fileRef.startsWith("file:")) {
      // Server-cached file reference — refresh TTL on access
      const fileId = fileRef.slice(5);
      refreshFile(fileId);
      const cached = getFile(fileId);
      if (!cached) {
        parts.push({ text: `[File not available: ${fileId}]` });
        continue;
      }
      mimeType = cached.mimeType;
      buffer = cached.buffer;
      data = cached.buffer.toString("base64");
    } else {
      // Base64 data URL
      const match = fileRef.match(/^data:([^;]+);base64,(.+)$/);
      if (!match) {
        parts.push({ text: `[Unrecognized file format]` });
        continue;
      }
      mimeType = match[1];
      data = match[2];
    }

    // For large files (>20MB), use Gemini's File API
    const sizeBytes = buffer ? buffer.length : (data.length * 3) / 4;
    if (sizeBytes > 20 * 1024 * 1024) {
      const blob = new Blob([buffer ?? Buffer.from(data, "base64")], { type: mimeType });
      const uploaded = await client.files.upload({
        file: blob,
        config: { mimeType },
      });
      // Wait for processing
      let geminiFile = uploaded;
      while (geminiFile.state === "PROCESSING") {
        await new Promise((r) => setTimeout(r, 2000));
        geminiFile = await client.files.get({ name: geminiFile.name! });
      }
      if (geminiFile.state === "FAILED") {
        throw new Error("File processing failed");
      }
      parts.push({ fileData: { fileUri: geminiFile.uri!, mimeType } });
    } else {
      parts.push({ inlineData: { mimeType, data } });
    }
  }

  // Use the image-capable model when the instruction requests visual output
  const wantsImage = /heatmap|overlay|annotate|highlight|mark|draw|visuali|generat.*image/i.test(input.instruction);
  const model = wantsImage ? IMAGE_CAPABLE_MODEL : ANALYSIS_MODEL;

  const config: any = {
    temperature: 0.4,
    maxOutputTokens: 8192,
    safetySettings: SAFETY_SETTINGS,
  };

  if (wantsImage) {
    config.responseModalities = ["TEXT", "IMAGE"];
  }

  const response = await client.models.generateContent({
    model,
    config,
    contents: [{ role: "user", parts }],
  });

  // Extract text and images from response
  const resultText: string[] = [];
  const generatedImageFileIds: string[] = [];

  const candidates = (response as any)?.candidates || [];
  for (const candidate of candidates) {
    for (const part of candidate.content?.parts || []) {
      if (part.text) {
        resultText.push(part.text);
      }
      if (part.inlineData) {
        const buf = Buffer.from(part.inlineData.data, "base64");
        const fileId = storeFile(buf, part.inlineData.mimeType, `analysis_${Date.now()}.png`);
        generatedImageFileIds.push(fileId);
      }
    }
  }

  // Fallback: try the simpler response accessor
  if (resultText.length === 0 && (response as any)?.text) {
    resultText.push((response as any).text);
  }

  // Calculate cost from token usage
  const usage = (response as any)?.usageMetadata;
  const credits = usage
    ? creditsForModelUsage(
        "gemini",
        model,
        usage.promptTokenCount || 0,
        usage.candidatesTokenCount || 0,
        usage.cachedContentTokenCount || 0,
      )
    : 0;

  return {
    text: resultText.join("\n") || "No analysis results returned.",
    generatedImageFileIds: generatedImageFileIds.length > 0 ? generatedImageFileIds : undefined,
    credits,
  };
}
