/**
 * economy-clothing.ts — CLOTHING, the first chain born as CONTENT
 * (civilization-emergence.md step 6d) — and, since the JSON milestone,
 * the first chain that lives in an ACTUAL EXTERNAL FILE: this module is
 * only the loader shim. The chain itself — wool grazed on the pasture
 * charter at the sheepfolds, cloth woven by population-anchored weavers
 * and sold over a shelved counter, household member 2 running the cloth
 * errands to the linen chest — is content/clothing.economy.json,
 * shape-checked by `parseEconomyDoc` at import (mods break at load).
 *
 * Calibration notes live as data in the file: industry-tier costs
 * append to the goods2 stagger (sheepfold 75 / weaver 100, cumulative —
 * generated by the compiler, not hand-arithmetic), and at ~12k souls
 * one weaver drawing 2.5 wool weaves min(2.5 × 1.6, 4) = 4 ≥ the 3.6
 * cloth need. It calibrated FIRST TRY — the compiler laws did the
 * structural work.
 */

import raw from "./content/clothing.economy.json";
import { parseEconomyDoc } from "./economy-json";
import type { EconomyDoc } from "./economy";

export const CLOTHING: EconomyDoc = parseEconomyDoc(raw, "clothing.economy.json");
