// CommuniAACteConversation.tsx
import { useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import {
  MessageCircle,
  Edit3,
  Image,
  Brain,
  Lightbulb,
  CheckCircle,
  Save,
  Share,
  X,
  History,
  Trash2,
  Upload,
  Eye,
  AlertTriangle,
  Crop as CropIcon,
  Share2,
  Copy,
  MessageSquare,
  Mail,
  MapPin,
  Clock,
  FileText,
  ArrowRight,
  ArrowLeft,
  Camera,
  FolderOpen,
  ChevronUp,
  Settings,
  User,
  Plus,
  Edit,
  Shield,
  Users,
  Minus,
  Calendar,
  Moon,
  Sun,
  LogOut,
  LogIn,
} from "lucide-react";
import type { Interpretation } from "@shared/schema";
import { toast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";

interface InterpretationResponse {
  success: boolean;
  interpretation: Interpretation;
  interpretedMeaning: string;
  analysis: string[];
  confidence: number;
  suggestedResponse: string;
}

type Props = {
  t: (k: string) => string;
  isRTL: boolean;
  language: string;
};

export function CommuniAACteConversation({ t, isRTL, language }: Props) {
  const { id } = useParams<{ id: string }>();

  const { data, isLoading, error } = useQuery({
    queryKey: ["/api/interpretations", id],
    queryFn: async () => {
      const res = await apiRequest('GET', `/api/interpretations/${id}`);
      return res.json() as Promise<InterpretationResponse>;
    },
  });

  if (isLoading) {
    return <div className="py-8 text-center">{t("ui.loading")}</div>;
  }

  if (error || !data) {
    return (
      <div className="py-8 text-center text-destructive">
        {t("history.loadError")}
      </div>
    );
  }

  const {
    interpretation,
    interpretedMeaning,
    analysis,
    confidence,
    suggestedResponse,
  } = data;

  // Share interpretation function
  const shareInterpretation = (type: "whatsapp" | "copy" | "email") => {
    const originalInput = interpretation.originalInput;

    const shareText =
      language === "he"
        ? `🗣️ פרשנות תקשורת מסייעת CommuniAACte
    
    📝 קלט מקורי: ${originalInput}
    
    💭 המשמעות המפורשת:
    "${interpretedMeaning}"
    
    🔍 ניתוח:
    ${analysis.map((point) => `• ${point}`).join("\n")}
    
    📊 רמת ביטחון: ${Math.round(confidence * 100)}%
    
    💡 תגובה מוצעת:
    "${suggestedResponse}"
    
    ---
    CommuniAACte מפרש תת"ח`
        : `🗣️ CommuniAACteAAC - Communication Interpretation
    
    📝 Original Input: ${originalInput}
    
    💭 Interpreted Meaning:
    "${interpretedMeaning}"
    
    🔍 Analysis:
    ${analysis.map((point) => `• ${point}`).join("\n")}
    
    📊 Confidence Level: ${Math.round(confidence * 100)}%
    
    💡 Suggested Response:
    "${suggestedResponse}"
    
    ---
    Generated by CommuniAACte`;

    switch (type) {
      case "whatsapp":
        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(
          shareText
        )}`;
        window.open(whatsappUrl, "_blank");
        break;
      case "copy":
        navigator.clipboard
          .writeText(shareText)
          .then(() => {
            toast({
              title: t("toast.copied"),
              description: t("toast.copiedDesc"),
            });
          })
          .catch(() => {
            toast({
              title: t("toast.copyFailed"),
              description: t("toast.copyFailedDesc"),
              variant: "destructive",
            });
          });
        break;
      case "email":
        const subject =
          language === "he"
            ? "פרשנות תקשורת מסייעת"
            : "AAC Communication Interpretation";
        const emailUrl = `mailto:?subject=${encodeURIComponent(
          subject
        )}&body=${encodeURIComponent(shareText)}`;
        window.location.href = emailUrl;
        break;
    }
  };

  const handleClear = () => {
    /*
    setCurrentInterpretation(null);
    setInputText("");
    setSelectedFile(null);
    setImagePreview(null);
    setCroppedImageBlob(null);
    */
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle
          className={`flex items-center gap-2 ${
            isRTL ? "w-full justify-end flex-row-reverse text-right" : ""
          }`}
        >
          <Lightbulb className="text-secondary" />
          {t("result.interpretation")}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Original Input Display */}
        <div>
          <h3 className="text-sm font-medium text-foreground mb-2">
            {t("result.aacText")}:
          </h3>
          <div className="bg-muted p-3 rounded-lg border">
            <span className="text-foreground font-mono">
              {interpretation.originalInput}
            </span>
          </div>
        </div>

        {/* Interpreted Meaning */}
        <div>
          <h3 className="text-sm font-medium text-foreground mb-2">
            {t("result.meaningShort")}:
          </h3>
          <div className="bg-blue-50 border border-blue-200 p-4 rounded-lg">
            <div className="flex items-start gap-3">
              <MessageCircle className="text-primary text-lg mt-1 flex-shrink-0" />
              <div>
                <p className="text-foreground text-base leading-relaxed">
                  "{interpretedMeaning}"
                </p>
                <Separator className="my-3 border-t-blue-200" />
                <h4 className="text-sm font-medium text-foreground mb-2">
                  {t("result.analysis")}:
                </h4>
                <ul className="text-sm text-muted-foreground space-y-1">
                  {analysis.map((point, index) => (
                    <li key={index}>• {point}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>

        {/* Share Section */}
        <div className="bg-muted/50 border border-border p-4 rounded-lg">
          <h4 className="text-sm font-medium text-foreground mb-3 flex items-center gap-2">
            <Share2 className="text-secondary" />
            {t("share.title")}
          </h4>
          <div className="flex flex-wrap gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => shareInterpretation("whatsapp")}
              className="flex items-center gap-2"
            >
              <MessageSquare className="h-4 w-4" />
              {t("share.whatsapp")}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => shareInterpretation("copy")}
              className="flex items-center gap-2"
            >
              <Copy className="h-4 w-4" />
              {t("share.copy")}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => shareInterpretation("email")}
              className="flex items-center gap-2"
            >
              <Mail className="h-4 w-4" />
              {t("share.email")}
            </Button>
          </div>
        </div>

        {/* Confidence & Suggestions */}
        <div className="grid sm:grid-cols-2 gap-4">
          <div className="bg-green-50 border border-green-200 p-4 rounded-lg">
            <h4 className="text-sm font-medium text-foreground mb-2 flex items-center gap-2">
              <CheckCircle className="text-secondary" />
              {t("result.confidence")}
            </h4>
            <div className="flex items-center gap-2">
              <Progress value={confidence * 100} className="flex-1" />
              <span className="text-sm font-medium text-foreground">
                {Math.round(confidence * 100)}%
              </span>
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              {confidence > 0.8
                ? t("result.confidenceHigh")
                : confidence > 0.6
                ? t("result.confidenceMedium")
                : t("result.confidenceLow")}
            </p>
          </div>

          <div className="bg-orange-50 border border-orange-200 p-4 rounded-lg">
            <h4 className="text-sm font-medium text-foreground mb-2 flex items-center gap-2">
              <Lightbulb className="text-orange-500" />
              {t("result.suggestedResponse")}
            </h4>
            <p className="text-sm text-foreground">"{suggestedResponse}"</p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-2 sm:gap-3 pt-4 border-t border-border">
          <Button
            variant="outline"
            onClick={handleClear}
            className="flex items-center gap-2 text-sm"
          >
            <Trash2 className="w-4 h-4" />
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
