// shared/space/planet-geography.ts
//
// THE GEOGRAPHY SEAM. Seagull generated a planet's surface from its own noise
// `heightAt`; here that is replaced by the shared world model — sphere
// tectonics → substrate → founding sites — while everything ABOUT the planet
// (how tall its mountains are, whether it has oceans, whether life settles it)
// comes from seagull's ported physics as `BodyFeatures`. So the terrain is
// generated by the current world model but its CHARACTER is the physics:
//
//   features.terrain.maxReliefKm  → relief amplitude (tectonic activity × gravity)
//   features.tectonicActivity     → plate count + orogeny epochs
//   effectiveSurfaceTempK + life  → ocean presence → continent/sea balance, rivers
//   features.terrain.roughness    → sub-cell detail
//
// The result is a `BuiltPlanet` (shared/planet): its `surface` is the
// `heightAt(dir)` the celestial-body renderer samples (Stage 4), and its
// `sites` are where the civ layer founds cities.

import type { GameSettings } from "../kernel/manifest.js";
import { buildPlanetWorld, type BuiltPlanet } from "../planet/planet-game.js";
import type { PlanetPalette } from "../planet/surface.js";
import {
  EARTHLIKE_VARIANTS, BARREN_VARIANTS, MOON_PALETTE, BARREN_YELLOW, ICE_WORLD, BARREN_DARK,
} from "../planet/palettes.js";
import type { ResolvedBody } from "./physics/index.js";

/** Earth radius in metres — the physics reports body radii in R_earth. */
export const R_EARTH_M = 6_371_000;

const clamp = (v: number, lo: number, hi: number): number => Math.max(lo, Math.min(hi, v));

/** Deterministic per-body geology seed (FNV-1a over the body id + system seed),
 *  so the same planet in the same system always grows the same geography. */
function bodySeed(id: string, systemSeed: number): number {
  let h = (systemSeed ^ 0x811c9dc5) >>> 0;
  for (let i = 0; i < id.length; i++) h = Math.imul(h ^ id.charCodeAt(i), 0x01000193) >>> 0;
  return h >>> 0;
}

export interface PlanetGeography {
  built: BuiltPlanet;
  /** Metres — the real physical radius the surface was built at. */
  radiusM: number;
  /** Whether liquid water pools (drives the ocean shell + settling). */
  hasOcean: boolean;
}

export interface GeographyOpts {
  /** Cube-sphere face resolution (cells per face edge). Orbital view = 24;
   *  raise for a closer descent. */
  faceN?: number;
  /** PLANET COMPRESSION (space-time-compression.md §5): the surface is built
   *  at the body's COMPRESSED radius (radius ÷ compression), so the terrain
   *  mesh, climate, and founding sites live on the same miniature sphere the
   *  physics body is. Relief stays real-height (storybook-steep terrain —
   *  the doc's vertical-compression choice). Default 1 (real scale). */
  compression?: number;
}

/** Pick a rocky world's terrain palette from its physics character (seagull's
 *  selectRockyPalette): moons grey, runaway-greenhouse yellow, habitable
 *  temperate = an earthlike variant, frozen white, scorched near-black, else a
 *  barren rock. Variant choice is deterministic per body. */
export function paletteFromFeatures(resolved: ResolvedBody, systemSeed: number): PlanetPalette {
  const { state, features } = resolved;
  const seed = bodySeed(resolved.body.id, systemSeed);
  if (state.totalMass < 0.1) return MOON_PALETTE;
  const Tk = features.effectiveSurfaceTempK;
  if (features.atmosphere.composition === "thick_co2") return BARREN_YELLOW;
  if (features.life.habitability > 0.3 && Tk >= 230 && Tk <= 320) {
    // Habitable + temperate reads as the familiar blue-ocean / green-land Earth.
    // (Alien red/violet/teal variants exist in palettes.ts if a world wants one,
    // but the recognisable home world stays blue.)
    return EARTHLIKE_VARIANTS[0];
  }
  if (Tk < 180) return ICE_WORLD;
  if (Tk > 700) return BARREN_DARK;
  return BARREN_VARIANTS[seed % BARREN_VARIANTS.length];
}

/** Does this world hold liquid water? Mirrors seagull's palette test
 *  (habitable temperature band + a real biosphere chance). */
export function hasOceanFeatures(resolved: ResolvedBody): boolean {
  const f = resolved.features;
  const t = f.effectiveSurfaceTempK;
  return f.life.habitability > 0.2 && t >= 250 && t <= 330;
}

/** Map a rocky body's physics character to the planet world model's params. */
export function geographyParamsFromFeatures(
  resolved: ResolvedBody,
  systemSeed: number,
  opts: GeographyOpts = {},
): { world: Record<string, unknown>; radiusM: number; hasOcean: boolean } {
  const f = resolved.features;
  if (f.terrain.maxReliefKm <= 0) {
    throw new Error(`planet-geography: body ${resolved.body.id} has no solid surface (a star or gas giant)`);
  }
  // The COMPRESSED radius — must match createCelestialBody's, or the terrain
  // sphere and the physics body disagree and the ground is unreachable.
  const compression = Math.max(1, opts.compression ?? 1);
  const radiusM = Math.max(1, (resolved.state.radius * R_EARTH_M) / compression);
  const ocean = hasOceanFeatures(resolved);

  // Relief: the physics gives a real mountain budget in km; convert to the
  // model's fraction-of-radius (maxElevation = relief·radius = maxReliefKm·1000 m).
  const relief = clamp((f.terrain.maxReliefKm * 1000) / radiusM, 0.001, 0.2);
  // Tectonic activity drives how many plates collide and for how long.
  const epochs = clamp(Math.round(150 + f.tectonicActivity * 450), 50, 900);
  const plates = clamp(Math.round(4 + f.tectonicActivity * 12), 3, 24);
  // Ocean worlds get a balanced land/sea split (Earth is ~30% land); dry worlds
  // are near-all land (their basins are just low, waterless ground). Kept low
  // enough that an oceaned world actually has visible seas, not near-all land.
  const continentR = ocean ? clamp(0.28 + f.life.habitability * 0.08, 0.25, 0.38) : 0.8;
  // Rivers + fertility + founding sites (the cities) only where life + water can.
  const settle = ocean && f.life.habitability > 0.2;
  const rain = ocean ? clamp(0.5 + f.life.habitability, 0.5, 3) : 0;
  const detail = clamp(f.terrain.roughness, 0.05, 1.2);
  // LARGE-SCALE CLIMATE (planet/climate.ts): the mean temperature is the
  // body's greenhouse-adjusted surface temperature, so cold worlds grow
  // big caps and hot worlds scorch; wetness rides the same physics that
  // drives the visible cloud deck (habitability + cloudCoverage), so a
  // world wrapped in water clouds is also rainy on the ground.
  const meanTempC = clamp(f.effectiveSurfaceTempK - 273, -80, 60);
  const wetness = ocean
    ? clamp(0.35 + 0.9 * f.life.habitability + 0.5 * f.atmosphere.cloudCoverage, 0.25, 2.5)
    : 0;

  return {
    world: {
      topology: { kind: "cube-sphere", faceN: opts.faceN ?? 24 },
      geology: { seed: bodySeed(resolved.body.id, systemSeed), epochs, plates, continentR },
      settle,
      rain,
      climate: { meanTempC, wetness },
      radius: radiusM,
      relief,
      detail,
      // TOWN-scale settlement density: the map-scope founding defaults were
      // tuned for regional grids; on a real-radius world their minSpacing 6
      // (~1,250 km at faceN 48) reads as continental capitals. Spacing 2
      // (~415 km) founds hundreds of candidates — still sparse next to a
      // real civilization (a village tier awaits region-refinement on
      // approach), but a functioning one.
      founding: { threshold: 60, radius: 2, minSpacing: 2, maxHarvest: 600 },
      // Colour comes from the body's physics, so Mars reads red, the Moon grey,
      // an ice world white — not every rocky planet as Earth.
      palette: paletteFromFeatures(resolved, systemSeed),
    },
    radiusM,
    hasOcean: ocean,
  };
}

/** Build a rocky body's real geography (tectonics → substrate → sites) from its
 *  physics features. Throws for stars / gas giants (no surface). */
export function buildPlanetGeography(
  resolved: ResolvedBody,
  systemSeed: number,
  opts: GeographyOpts = {},
): PlanetGeography {
  const { world, radiusM, hasOcean } = geographyParamsFromFeatures(resolved, systemSeed, opts);
  const game: GameSettings = {
    scope: "planet",
    world,
    initialFocus: null,
    avatar: false,
    avatarSpecies: "human",
    canFly: false,
    creativeMode: false,
    entities: null,
    scale: null,
    transport: null,
    culture: null,
  };
  return { built: buildPlanetWorld(game, `body:${resolved.body.id}`), radiusM, hasOcean };
}
