const puppeteer=require("puppeteer"),fs=require("fs"),path=require("path");
const port=process.argv[2]||"5185";
(async()=>{
  const outDir=path.join(__dirname,"caps-clouds");
  const b=await puppeteer.launch({headless:"new",args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"]});
  const p=await b.newPage();await p.setViewport({width:600,height:600});
  p.on("pageerror",e=>console.log("ERR",e.message));
  await p.goto(`http://localhost:${port}/cloud-lab.html`,{waitUntil:"networkidle0"});
  await p.waitForFunction(()=>typeof window.__labReady==="function",{timeout:20000});
  await p.evaluate(()=>window.__labGoto("fair-weather-ground"));
  await p.evaluate(()=>window.__labSetRenderer("blobs"));
  await p.waitForFunction(()=>window.__labReady(),{timeout:120000});
  await p.evaluate(()=>window.__labSetSite(5,20));
  await p.evaluate(()=>window.__labSetCam(9000,0,-60));
  await new Promise(z=>setTimeout(z,800));
  const st=JSON.parse(await p.evaluate(()=>window.__labStats()));
  await p.screenshot({path:path.join(outDir,"dbg_neutral.png")});
  console.log("sprites",st.sprites,"alt",st.altM,"pitch",st.pitchDeg);
  await b.close();
})();
